name: Preset Hub CI

on:
  push:
    paths:
      - "Splatoon.PresetHub.Core/**"
      - "Splatoon.PresetHub.Core.Tests/**"
      - "Splatoon/Modules/PresetHub/**"
      - "Splatoon/Gui/PresetHub/**"
      - "Splatoon/Serializables/Layout.cs"
      - "Splatoon/SplatoonScripting/ScriptingProcessor.cs"
      - "Splatoon/Utility/Utils.cs"
      - "Splatoon/Splatoon.csproj"
      - "Splatoon/Splatoon.cs"
      - ".github/workflows/Preset Hub CI.yml"
  pull_request:
    paths:
      - "Splatoon.PresetHub.Core/**"
      - "Splatoon.PresetHub.Core.Tests/**"
      - "Splatoon/Modules/PresetHub/**"
      - "Splatoon/Gui/PresetHub/**"
      - "Splatoon/Serializables/Layout.cs"
      - "Splatoon/SplatoonScripting/ScriptingProcessor.cs"
      - "Splatoon/Utility/Utils.cs"
      - "Splatoon/Splatoon.csproj"
      - "Splatoon/Splatoon.cs"
      - ".github/workflows/Preset Hub CI.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  core-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet restore Splatoon.PresetHub.Core.Tests/Splatoon.PresetHub.Core.Tests.csproj
      - name: Test
        run: dotnet test Splatoon.PresetHub.Core.Tests/Splatoon.PresetHub.Core.Tests.csproj --no-restore --configuration Release
